# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fffed52b5bbf61995136993fc2f86b73d686696c0b302137ca05cfbc7078fde34189d2aceab276d19d81af51fbbb1962c90401000d270cc49fca947eb251276c

test:
  secret_key_base: 510cc9e197931bdcb97df0b9a3684d954292a9dd47eeb179b5dede879f6bd923c81f78ae0daebf01e37888614a833189873da5560f3a1f8ff295904030ea96f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
